"""
Interactive setup wizard.

Asks the user which provider to use (Claude / ChatGPT / Gemini / DeepSeek),
prompts for the API key, and stores it in `.env` (gitignored). Also writes
`CVO_PROVIDER=<choice>` so future runs default to that provider.

Triggered automatically by `cvo run` when no API key is present, and
exposed as `cvo setup` for explicit re-runs.
"""

from __future__ import annotations

import getpass
import os
import sys
from pathlib import Path

from .providers import (
    PROVIDER_ORDER,
    PROVIDERS,
    has_api_key,
    provider_meta,
    resolve_active_provider,
)


# ──────────────────────────────────────────────────────────────────────
# Tiny color helpers (duplicated from cli.py to avoid the circular import)
# ──────────────────────────────────────────────────────────────────────
def _supports_color() -> bool:
    return sys.stdout.isatty() and os.getenv("NO_COLOR") is None


def _c(text: str, code: str) -> str:
    return f"\033[{code}m{text}\033[0m" if _supports_color() else text


def _cyan(s: str)    -> str: return _c(s, "36")
def _green(s: str)   -> str: return _c(s, "32")
def _yellow(s: str)  -> str: return _c(s, "33")
def _red(s: str)     -> str: return _c(s, "31")
def _bold(s: str)    -> str: return _c(s, "1")
def _dim(s: str)     -> str: return _c(s, "2;37")


def _info(msg: str): print(_cyan(f"ℹ  {msg}"))
def _ok(msg: str):   print(_green(f"✓  {msg}"))
def _warn(msg: str): print(_yellow(f"⚠  {msg}"))
def _err(msg: str):  print(_red(f"✗  {msg}"))


# ──────────────────────────────────────────────────────────────────────
# .env read / write
# ──────────────────────────────────────────────────────────────────────
def _project_env_path() -> Path:
    """Always anchor .env at the current working directory."""
    return Path.cwd() / ".env"


def _read_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    out: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            out[key] = value
    return out


def _write_env_file(path: Path, values: dict[str, str]) -> None:
    """
    Rewrite .env keeping order: comments at top, then known providers in
    PROVIDER_ORDER, then CVO_PROVIDER, then any extra keys we did not touch.
    """
    known_keys = {provider_meta(p)["env_key"] for p in PROVIDER_ORDER}
    known_keys.add("CVO_PROVIDER")

    lines: list[str] = [
        "# cv-optimizer — generated by `cvo setup` (or auto-prompt on first run).",
        "# This file is gitignored. Keep your API keys here only.",
        "",
        "# Active provider used by `cvo run` (claude | openai | gemini | deepseek).",
        f"CVO_PROVIDER={values.get('CVO_PROVIDER', 'claude')}",
        "",
        "# API keys — only the one for the active provider is required.",
    ]
    for p in PROVIDER_ORDER:
        env_key = provider_meta(p)["env_key"]
        lines.append(f"{env_key}={values.get(env_key, '')}")

    # Preserve any extra unrelated keys the user may have added.
    extras = {k: v for k, v in values.items() if k not in known_keys}
    if extras:
        lines.append("")
        lines.append("# Other keys preserved from prior .env:")
        for k in sorted(extras.keys()):
            lines.append(f"{k}={extras[k]}")

    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


# ──────────────────────────────────────────────────────────────────────
# Wizard
# ──────────────────────────────────────────────────────────────────────
def _prompt_provider_choice() -> str:
    print()
    print(_bold("Choose an LLM provider:"))
    for i, p in enumerate(PROVIDER_ORDER, start=1):
        meta = PROVIDERS[p]
        marker = _green(" (configured)") if has_api_key(p) else _dim(" (not configured)")
        print(f"  {i}) {meta['display_name']}{marker}")
    print()

    while True:
        try:
            raw = input("Pick 1-4 [1]: ").strip()
        except EOFError:
            raw = ""
        if not raw:
            return PROVIDER_ORDER[0]
        if raw.isdigit() and 1 <= int(raw) <= len(PROVIDER_ORDER):
            return PROVIDER_ORDER[int(raw) - 1]
        if raw.lower() in PROVIDER_ORDER:
            return raw.lower()
        _warn("Invalid choice. Type 1, 2, 3 or 4.")


def _prompt_api_key(provider: str) -> str:
    meta = provider_meta(provider)
    print()
    print(_bold(f"API key for {meta['display_name']}"))
    print(_dim(f"   Get one at: {meta['key_url']}"))
    print(_dim("   The key is hidden as you type and stored in .env (gitignored)."))
    while True:
        try:
            key = getpass.getpass("Paste API key (or press Enter to skip): ").strip()
        except (KeyboardInterrupt, EOFError):
            print()
            _warn("Skipping key entry.")
            return ""
        if not key:
            _warn("No key entered. You can re-run `cvo setup` later.")
            return ""
        # Trivial sanity check — most provider keys are 30+ chars.
        if len(key) < 16:
            _warn("That looks short for an API key. Continuing anyway.")
        return key


def run_wizard(
    preselected_provider: str | None = None,
    force: bool = False,
) -> str:
    """
    Run the interactive wizard.

    Args:
      preselected_provider: skip the picker and use this provider.
      force: even if the key is already set, ask again.

    Returns:
      The provider name selected. .env is updated as a side effect.
      The current process env is also updated so the run can continue
      without restarting.
    """
    print()
    print(_bold("── cvo setup ───────────────────────────────────────────────"))
    print(_dim("   Configure which LLM provider cv-optimizer uses, and store"))
    print(_dim("   its API key in .env (gitignored, never committed)."))

    provider = preselected_provider or _prompt_provider_choice()
    meta = provider_meta(provider)
    _info(f"Selected: {meta['display_name']}")

    env_path = _project_env_path()
    values = _read_env_file(env_path)

    existing = values.get(meta["env_key"]) or os.getenv(meta["env_key"], "")
    key: str = ""
    if existing and not force:
        _ok(f"{meta['env_key']} already set — keeping existing value.")
        key = existing
    else:
        key = _prompt_api_key(provider)
        if not key:
            # Don't overwrite an existing key with empty.
            key = existing

    values[meta["env_key"]] = key
    values["CVO_PROVIDER"] = provider
    _write_env_file(env_path, values)
    _ok(f"Wrote .env at: {env_path}")

    # Make the new values available to the current process so `cvo run`
    # can continue immediately after the wizard.
    if key:
        os.environ[meta["env_key"]] = key
    os.environ["CVO_PROVIDER"] = provider

    print()
    return provider


def ensure_provider_configured(cli_choice: str | None = None) -> str:
    """
    Resolve the active provider; if its API key is missing, run the wizard.
    Returns the provider that ends up active.
    """
    provider = resolve_active_provider(cli_choice)
    if has_api_key(provider):
        return provider
    _warn(
        f"No API key found for the active provider ({provider}). "
        "Launching setup wizard…"
    )
    return run_wizard(preselected_provider=cli_choice)
